from cube import Cube

def main():
    cube = Cube()
    cube.rotate(2,1)
    cube.rotate(1,0)
    initial = cube.clone()
    #breadth-first search:
    cube.rotate(0,0)
    print(cube)
    cube = initial.clone()

    cube.rotate(0,1)
    print(cube)
    cube = initial.clone()

    cube.rotate(1,0)
    print(cube)
    cube = initial.clone()

    cube.rotate(1,1)
    print(cube)
    cube = initial.clone()

    cube.rotate(2,0)
    print(cube)
    cube = initial.clone()

    cube.rotate(2,1)
    print(cube)
    cube = initial.clone()


    cube.rotate(0,0)
    cube.rotate(0,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,0)
    cube.rotate(1,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,0)
    cube.rotate(1,1)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,0)
    cube.rotate(2,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,0)
    cube.rotate(2,1)
    print(cube)
    cube = initial.clone()

    cube.rotate(0,1)
    cube.rotate(0,1)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,1)
    cube.rotate(1,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,1)
    cube.rotate(1,1)
    print(cube)

    '''
    cube = initial.clone()
    cube.rotate(0,1)
    cube.rotate(2,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(0,1)
    cube.rotate(2,1)
    print(cube)
    cube = initial.clone()

    cube.rotate(1,0)
    cube.rotate(0,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,0)
    cube.rotate(0,1)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,0)
    cube.rotate(1,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,0)
    cube.rotate(2,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,0)
    cube.rotate(2,1)
    print(cube)
    cube = initial.clone()

    cube.rotate(1,1)
    cube.rotate(0,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,1)
    cube.rotate(0,1)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,1)
    cube.rotate(1,0)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,1)
    cube.rotate(1,1)
    print(cube)
    cube = initial.clone()
    cube.rotate(1,1)
    cube.rotate(2,0)
    print(cube)

'''


    
    
if __name__ == "__main__":
    main()